<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/"><channel><title>Dbfs on amardeepsidhu.com</title><link>https://amardeepsidhu.com/tags/dbfs/</link><description>Recent content in Dbfs on amardeepsidhu.com</description><generator>Hugo -- 0.147.9</generator><language>en</language><lastBuildDate>Sat, 05 Jun 2021 20:19:37 +0530</lastBuildDate><atom:link href="https://amardeepsidhu.com/tags/dbfs/index.xml" rel="self" type="application/rss+xml"/><item><title>File system already present at specified mount point /dbfs_direct</title><link>https://amardeepsidhu.com/blog/2021/06/05/file-system-already-present-at-specified-mount-point-dbfs_direct/</link><pubDate>Sat, 05 Jun 2021 20:19:37 +0530</pubDate><guid>https://amardeepsidhu.com/blog/2021/06/05/file-system-already-present-at-specified-mount-point-dbfs_direct/</guid><description>&lt;p>It was actually funny. So thought about posting it that sometimes how we can miss the absolute basics. This customer is using a virtualized Exadata with multiple VMs. One VM hosts the database meant to be used for dbfs and another VM connects to this DB over IB to mount dbfs file system using dbfs_client. One day VMs were rebooted and due to some reason the dbfs filesystem didn&amp;rsquo;t mount on startup. It went on for few days and they couldn&amp;rsquo;t mount it. One day I got a chance to look at it and the error they were facing was:&lt;/p></description></item></channel></rss>